
export const units: string[] = [
    "Adept",
    "Adept Phase Shift",
    "Arbiter MP",
    "Archon",
    "Baneling",
    // "Baneling Burrowed",
    // "Baneling Cocoon",
    "Banshee",
    "Battlecruiser",
    "Broodling",
    // "Broodling Escort",
    "Brood Lord",
    // "Brood Lord Cocoon",
    "Carrier",
    "Caustic Spray Missile",
    "Changeling",
    // "Changeling Marine",
    // "Changeling Marine Shield",
    // "Changeling Zealot",
    // "Changeling Zergling",
    // "Changeling Zergling Wings",
    "Colossus",
    "Corruptor",
    // "Corsair",
    // "Creep Tumor Missile",
    "Cyclone",
    // "Cyclone Missile",
    // "Cyclone Missile Large",
    // "Cyclone Missile Large Air",
    // "Cyclone Missile Large Air Alternative",
    "Dark Templar",
    // "Defiler MP",
    // "Defiler MP Burrowed",
    // "Devourer Cocoon MP",
    "Disruptor",
    // "Disruptor Phased",
    "Drone",
    // "Drone Burrowed",
    "Egg",
    // "Force Field",
    // "Fungal Growth Missile",
    "Ghost",
    // "Ghost Alternate",
    // "Ghost Nova",
    "Brood Lord",
    // "Guardian Cocoon MP",
    // "Guardian MP",
    "Hellion",
    // "Hellion Tank",
    // "HERC",
    // "High Templar",
    // "High Templar Skin Preview",
    "Hydralisk",
    // "Hydralisk Burrowed",
    // "Hydralisk Impale Missile",
    "Immortal",
    // "Infested Terrans Egg",
    // "Infested Terrans Egg Placement",
    "Infestor",
    // "Infestor Burrowed",
    // "Infestor Terran",
    // "Infestor Terran Burrowed",
    "Interceptor",
    "Larva",
    "Liberator",
    // "Liberator AG",
    // "Liberator AG Missile",
    // "Liberator Damage Missile",
    // "Liberator Missile",
    // "Liberator Skin Preview",
    "Locust",
    // "Locust MP Flying",
    // "Lurker MP",
    // "Lurker MP Burrowed",
    // "Lurker MP Egg",
    "Marauder",
    "Marine",
    "Medivac",
    "Mothership",
    // "Mothership Core",
    "MULE",
    "Mutalisk",
    // "Neural Parasite Tentacle Missile",
    "Nuke",
    "Observer",
    // "Observer Siege Mode",
    "Oracle",
    "Overlord",
    // "Overlord Cocoon",
    // "Overlord Transport",
    "Overseer",
    // "Overseer Siege Mode",
    // "Parasitic Bomb Missile",
    "Phoenix",
    // "Preview Bunker Upgraded",
    "Probe",
    // "Protoss Snake Segment Demo",
    "Queen",
    // "Queen Burrowed",
    // "Queen MP",
    // "Queen MP Ensnare Missile",
    // "Queen MP Spawn Broodlings Missile",
    "Ravager",
    // "Ravager Burrowed",
    // "Ravager Cocoon",
    // "Ravager Corrosive Bile Missile",
    "Raven",
    // "Raven Scrambler Missile",
    "Reaper",
    // "Release Interceptors Beacon",
    // "Replicant",
    "Roach",
    // "Roach Burrowed",
    // "Scourge MP",
    "SCV",
    "Seeker Missile",
    "Sentry",
    "Siege Tank",
    // "Siege Tank Sieged",
    // "Siege Tank Skin Preview",
    "Stalker",
    "Swarm Host",
    // "Swarm Host Burrowed MP",
    // "Swarm Host MP",
    // "Tempest",
    // "Test Zerg",
    "Thor",
    // "Thor AA Lance",
    // "Thor AP",
    "Tower Mine",
    // "Transport Overlord Cocoon",
    "Ultralisk",
    // "Ultralisk Burrowed",
    "Viking",
    // "Viking Assault",
    // "Viking Fighter",
    "Viper",
    // "Void MP Immortal Revive Corpse",
    "Void Ray",
    "War Hound",
    "Warp Prism",
    // "Warp Prism Phasing",
    // "Warp Prism Skin Preview",
    "Widow Mine",
    // "Widow Mine Burrowed",
    "Yoink Missile",
    // "Yoink Siege Tank Missile",
    // "Yoink Viking Air Missile",
    // "Yoink Viking Ground Missile",
    "Zealot",
    "Zergling",
    // "Zergling Burrowed",
]

export const buildings: string[] = [
    "Armory",
    "Assimilator",
    // "Assimilator Rich",
    "Auto Turret",
    "Baneling Nest",
    "Barracks",
    // "Barracks Flying",
    "Reactor",
    "Tech Lab",
    "Bunker",
    // "Bypass Armor Drone",
    "Command Center",
    // "Command Center Flying",
    "Creep Tumor",
    // "Creep Tumor Burrowed",
    // "Creep Tumor Queen",
    "Cybernetics Core",
    "Dark Shrine",
    "Engineering Bay",
    "Evolution Chamber",
    "Extractor",
    // "Extractor Rich",
    "Factory",
    // "Factory Flying",
    // "Factory Reactor",
    // "Factory Tech Lab",
    "Fleet Beacon",
    "Forge",
    "Fusion Core",
    "Gateway",
    "Ghost Academy",
    "Greater Spire",
    "Hatchery",
    "Hive",
    "Hydralisk Den",
    "Infestation Pit",
    "KD8Charge",
    "Lair",
    "Lurker Den",
    "Missile Turret",
    "Nexus",
    "Nydus",
    // "Nydus Canal Attacker",
    // "Nydus Canal Creeper",
    // "Nydus Network",
    "Oracle Stasis Trap",
    "Orbital Command",
    // "Orbital Command Flying",
    "Photon Cannon",
    "Planetary Fortress",
    "Point Defense Drone",
    "Pylon",
    "Pylon Overcharged",
    // "Raven Repair Drone",
    "Reactor",
    "Refinery",
    // "Refinery Rich",
    "Renegade Missile Turret",
    "Resource Blocker",
    "Roach Warren",
    "Robotics Bay",
    "Robotics Facility",
    "Sensor Tower",
    "Shield Battery",
    "Spawning Pool",
    "Spine Crawler",
    // "Spine Crawler Uprooted",
    "Spire",
    "Spore Crawler",
    // "Spore Crawler Uprooted",
    "Stargate",
    "Starport",
    // "Starport Flying",
    // "Starport Reactor",
    // "Starport Tech Lab",
    "Supply Depot",
    // "Supply Depot Lowered",
    "Tech Lab",
    "Templar Archive",
    "Twilight Council",
    "Ultralisk Cavern",
    "Warp Gate",
]

export const weapons: string[] = [
    "Adept",
    "Arbiter MP Weapon",
    "Psionic Shockwave",
    "Auto Turret",
    "Backlash Rockets",
    "Needle Claws",
    "Broodling Strike",
    "Guass Rifle",
    "Psi Blades",
    "Claws",
    "Thermal Lances",
    "Parasite Spore",
    "Neutron Flare",
    "Typhoon Missile Pod",
    "Warp Blades",
    "Spines",
    "C10Canister Rifle",
    "Guardian MP Weapon",
    "Infernal Flame Thrower",
    "Hellion Tank",
    "HERC Weapon",
    "High Templar Weapon",
    "Needle Spines",
    "Phase Disruptors",
    "Infested Acid Spines",
    "Infested Guass Rifle",
    "Interceptor Beam",
    "Liberator Missile Launchers",
    "Liberator AG Weapon",
    "Locust MP",
    "Lurker MP",
    "Punisher Grenades",
    "Longbolt Missile",
    "Mothership Beam",
    "Repulsor Cannon",
    "Glaive Wurm",
    "Nydus Canal Attacker Weapon",
    "Oracle Display Dummy",
    "Ion Cannons",
    "Photon Cannon",
    "Twin Ibiks Cannon",
    "Particle Beam",
    "Acid Spines",
    "Talons Missile",
    "Ravager Weapon",
    "P38Scythe Guass Pistol",
    "Renegade Longbolt Missile",
    "Acid Saliva",
    "Scourge MP Weapon",
    "Fusion Cutter",
    "90mm Cannons",
    "Crucio Shock Cannon",
    "Impaler Tentacle",
    "Acid Spew",
    "Particle Disruptors",
    "Tempest",
    "Tempest Ground",
    "Javelin Missile Launchers",
    "Thors Hammer",
    "Lance Missile Launchers",
    "Kaiser Blades",
    "Twin Gatling Cannon",
    "Lanzer Torpedoes",
    "War Hound",
]

// Articles, that can be ignored
export const articles = ['a', 'an', 'the']
export const fillers = ['of', 'or', 'is', 'if', 'what', 'how', 'much']
